services:
  # This postgres container will its data even after restarts
  # It will use .data/pg as volume ( currently in some reason, it doesn't keep files there, but it works :) )
  pg:
    image: postgres:14-alpine
    container_name: pg
    ports:
      - 3002:5432
    volumes:
      - .data/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=app-user
      - POSTGRES_USER=app-user
      - POSTGRES_DB=app-db
    networks:
      - app_net

networks:
  app_net: